### ISSUE TITLE
Creeper Crash

### ISSUE THREAD

**Issue by Dr-WeiAL** [Insane96/EnhancedAI#86] opened 2023-04-07 12:09 UTC
**Describe the bug**  
The game crashed after encountering a creeper
Very low probability of crashing, I don't understand why

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.16.5
 - Forge: 36.2.39
 - Enhanced AI: 1.2.3
 - InsaneLib: 1.4.2

**Steps to reproduce**  
1.   Encountered a Creeper and it seemed to explode
2.   And then the game crashed

**Logs**  
https://pastebin.com/csnQB97J

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Uncertain

**Comment by Insane96** [comment] 2023-04-07 12:35
Can't reproduce with EhancedAI only, find the mod conflicting.

**Comment by Insane96** [comment] 2023-04-20 19:37
No reply in two weeks, closing

**Closed as completed by Insane96** 2023-04-20 19:37 UTC
Labels: bug, on hold
