### ISSUE TITLE
The monster can see the player in the Invisibility state

### ISSUE THREAD

**Issue by Dr-WeiAL** [Insane96/EnhancedAI#88] opened 2023-04-16 03:55 UTC
**Describe the bug**  
When using Better Invisibility I found that monsters would still attack me in stealth, then I created a separate modpack that only contained EnhancedAI and found that it was EnhancedAI that caused the monsters to see the player, and I couldn't find an option in the config file to disable the monsters from seeing the player in stealth

**Versions where you encountered the problem (Use the exact version numbers, not 'latest' or similar):**  
 - Minecraft: 1.18.2
 - Forge: 40.2.1
 - Enhanced AI: 1.6.5
 - InsaneLib: 1.5.3

**Steps to reproduce**  
1.   Invisibility
2.   Switch to survival mode
3.   Monsters will ignore Invisibility to attack players

**Screenshots**  
![image](https://user-images.githubusercontent.com/47446553/232265568-ff6879ff-721f-4cdf-b9a7-225980443689.png)

**Logs**  
This should not require a log, right?

**Can the issue be reproduced with EnhancedAI only (or with a minimal set of mods)?**  
Yes

**Comment by Insane96** [comment] 2023-04-16 06:49
This is a vanilla feature. Players with invisibility have reduced sight range, but not completely invisible.
https://minecraft.fandom.com/wiki/Invisibility#Notes

This would require a compat addition for Better Invisibility

**Comment by Dr-WeiAL** [comment] 2023-04-16 06:56
Ok I see, that means EnhancedAI will be compatible with Better Invisibility afterwards?

**Comment by Insane96** [comment] 2023-04-16 06:57
Will probably not as Better Invisibility is not open source.
Just check if the vanilla behaviour works (try without armor and see if the detection range is 7%), if not, then this is on Better Invisilbility side.

**Comment by Dr-WeiAL** [comment] 2023-04-16 07:03
I tried, if not wearing armor, the monster will not see me
Well, I'll try to send an issue to the author of Better Invisibility

**Comment by Insane96** [comment] 2023-04-20 19:42
I'm closing this as works as intended

**Closed as completed by Insane96** 2023-04-20 19:42 UTC
Labels: bug, invalid, other mod
