### ISSUE TITLE
[CRASH 1.16.5] Null Pointer Exception with zombie digging fillTargetBlocks

### ISSUE THREAD

**Issue by NighthowlerStudios** [Insane96/EnhancedAI#84] opened 2023-03-26 18:52 UTC
**Describe the bug**  
I am no longer sure the cause of this issue as the information I had gathered watching it happen was somehow incorrect and cannot be reproduced the same way.  I will be continuing to test and will send replies if I find something in the future.

**Versions (don't use "latest"):**  
 - Minecraft: 1.16.5
 - Forge: 36.2.39
 - Enhanced AI: 1.2.3
 - InsaneLib: 1.4.2

**Steps to reproduce**  
N/A until further notice

**Logs**  
https://pastebin.com/6xHqmURT

**Can the issue be reproduced with EnhancedAI only?**  
No, still seeking mod conflict.

**Comment by Insane96** [comment] 2023-03-26 18:55
> Crashes when the zombie attempts to replace the block with air

Not true, the game crashes when getting blocks to mine

> Enhanced AI: any
  InsaneLib: any

Nice, really useful

> Can the issue be reproduced with EnhancedAI only?
  Not tested
  
Do it, this has never been an issue  
Some other mod seems to be messing with the target of the zombie.
Reproduce this with EnhancedAI only (+ any other mod messing with it) and I _might_ fix this

**Comment by NighthowlerStudios** [comment] 2023-03-26 19:40
> Enhanced AI: any
> InsaneLib: any

> Nice, really useful

I don't appreciate the sass, that was not necessary.   This information is accurate for my modpack instance.  I have attempted downgrading to no avail.  So yes, absolutely every version of Enhanced AI that has the feature is broken.

I can see now your intention was "what version are you using", not "what version is the bug encountered on".  it may help to be more clear on that in your issue template.

>Can the issue be reproduced with EnhancedAI only?
>Not tested

>Do it, this has never been an issue

 haven't found the time to do this yet as I have university work to grind out on.  Testing against 300+ mods would take ages, I hope you know.  But I will try as soon as I can.  Firstly with the mod alone, which I can do.  Then afterward finding the mod conflict if possible.

**Comment by NighthowlerStudios** [comment] 2023-03-26 20:13
I have updated the issue with relevant information changes as watching footage of the issue with my friend seems to be incorrect in any reproduction attempts.  Until we know for certain what caused it we can assume this crash is random somehow until further notice.  I will post new information if I find it, if I can even get it to crash again, that is.

Is there any chance you could simply make the code NPE safe for the time being?  I can't view the 1.16.5 branch to inspect it myself as it's not on this git.

**Comment by NighthowlerStudios** [comment] 2023-03-26 20:17
I have also posted our "currently installed versions" of the mod as you seem to be requesting.

**Comment by Insane96** [comment] 2023-03-26 22:00
> I hope you know

I know, that's why I ask ppls to reproduce it.

> what version is the bug encountered on

That's not necessary, it's quite obvious I'm asking for the versions you've encountered the bug on, not random versions. I see you're trying to find out if the bug existed in previous version, but that's not really useful. It's much easier to find and squash the bug on the latest version than just backtracking to understand what went wrong between versions.

> I can't view the 1.16.5 branch to inspect it myself as it's not on this git.

It is, the master branch is 1.16.5 (I will rename it now, so it's clear)

> Is there any chance you could simply make the code NPE safe for the time being

This doesn't seem a good fix. The problem happens as the Goal starts and even if right before it's checked if the target is a player (and thus not null) as soon as it starts the game crashes. I will try to investigate further.

If you want to check it out, this is where the game crashes   
https://github.com/Insane96/EnhancedAI/blob/1.16.5/src/main/java/insane96mcp/enhancedai/modules/zombie/ai/AIZombieDigger.java#L202
And this is where the check is made right before 
 https://github.com/Insane96/EnhancedAI/blob/1.16.5/src/main/java/insane96mcp/enhancedai/modules/zombie/ai/AIZombieDigger.java#L55

**Comment by NighthowlerStudios** [comment] 2023-03-26 22:12
Thanks for the information, I will fork and insert some debugs to see if i can trace the code a bit better.  it's possible somehow a mod may have ruined Goals, I thought it was Roadrunner but I have Roadrunner's goal mixins disabled.  I will be doing most of this next weekend when i have more time scheduled

**Comment by Insane96** [comment] 2023-04-20 19:43
Some time has passed and 1.16.5 is not really supported anymore, so closing

**Closed as completed by Insane96** 2023-04-20 19:43 UTC
Labels: bug
